version: '3.9'

services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: database
    image: mysql:8.4
    restart: on-failure
    healthcheck:
      test: "/usr/bin/mysql -uroot -proot -e \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

