version: '3.4'

networks:
  tech-challenge-net:
    driver: bridge


services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9101:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - tech-challenge-net
  
  db:
    environment:
      MYSQL_DATABASE: 'app-database'   
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'root'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    networks:
      - tech-challenge-net