apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: matheusfernandesluz/api-tech-challenge:3.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 30m
              memory: "512Mi"
          env:
          - name: ConnectionStrings__Mysql
            valueFrom: 
              secretKeyRef:
                name: api-secret
                key: API_CONNECTION_STRING