apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  serviceName: "database"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: database
        image: mysql:8
        ports:
        - containerPort: 3306
          name: database
        envFrom:
          - configMapRef:
              name: db-configmap
        volumeMounts:
        - name: pv-database
          mountPath: /var/lib/mysql
      volumes:
      - name: pv-database
        persistentVolumeClaim:
          claimName: pvc-database

